sonar.projectKey=VehicleManagement.Frontend
sonar.projectName=VehicleManagement Frontend
sonar.projectVersion=1.0

# Path to source files
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,src/environments/**,src/test-setup.ts,**/*.spec.ts,**/*.scss

# Path to test files
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Coverage report path
sonar.javascript.lcov.reportPaths=coverage/vehicle-management-ui/lcov.info
sonar.typescript.tsconfigPath=tsconfig.sonar.json
